### ISSUE TITLE
Opzoeken Afmetingen

### ISSUE THREAD

**Issue by RubenBelligh** [vives-project-xp/GreenhouseSensoring#37]
We gaan een doosje maken voor de sensoren mooi in op te bergen. Hiervoor heb je de afmetingen nodig van de verschillende componenten.

temperatuur/Vochtigheid sensor: 13,5 x 10,5mm
CO2 sensor:  39 x 20mm
Lichtintensiteit sensor:  13,9 x 18.55mm

**Comment by Kenrie19** [comment]
Niet gevonden -> wachten op esp om correcte afmetingen te weten
