### ISSUE TITLE
Doorsturen waardes naar Home assistant (+light&heat?)

### ISSUE THREAD

**Issue by vyx04** [vives-project-xp/GreenhouseSensoring#58]
- NPK moet nog doorgestuurd worden (3 verschillende waardes)
- momenteel is type van elke waarde nog TEMPERATURE, moet dus nog aangepast worden.
- light&heat wil mogelijk rechtstreeks data van lichtsensor.

**Comment by Kenrie19** [comment]
Nieuwe Esp moet toegevoegd worden
