### ISSUE TITLE
Ontwerpen doosje voor de sensoren 2.0

### ISSUE THREAD

**Issue by RubenBelligh** [vives-project-xp/GreenhouseSensoring#60]
Ik heb een doosje ontworpen voor de sensoren. Maar hier hadden we een probleem. We konden blijkbaar niet printen in doorzichtig PLA waardoor de lichtsensor dus niet optimaal zou werken. Nu hebben we gekozen om een doorzichtig doosje te gebruiken.

**Comment by vyx04** [comment]
Opgelost: lichtsensor samen met omgevingstemperatuur- en CO2-sensor in een apart doorzicht doosje geplaatst.
